# Generated by Django 5.2.7 on 2025-11-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('progress', 'progress'), ('pending', 'pending'), ('blocked', 'blocked'), ('done', 'done')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('progress', 'progress'), ('pending', 'pending'), ('blocked', 'blocked'), ('done', 'done')], default='new', max_length=20),
        ),
    ]
